"""initial_system_models

Revision ID: 1031cf14f568
Revises: 
Create Date: 2026-02-21 11:24:35.456928

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1031cf14f568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_type',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dict_type_code'), 'dict_type', ['code'], unique=True)
    op.create_index(op.f('ix_dict_type_name'), 'dict_type', ['name'], unique=False)
    op.create_table('organization',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_table('robot',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('robot_state', sa.Integer(), nullable=False),
    sa.Column('current_task', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('latitude', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('longitude', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('pending_command', sa.Text(), nullable=True),
    sa.Column('user_info_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('needs_user_update', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_code'), 'robot', ['code'], unique=True)
    op.create_table('system_log',
    sa.Column('log_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('robot_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_log_level'), 'system_log', ['level'], unique=False)
    op.create_index(op.f('ix_system_log_log_type'), 'system_log', ['log_type'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('dict_item',
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('dict_type_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dict_type_id'], ['dict_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_info',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('weight', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('card_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('soldier_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('disease', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('bucankao', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bmi', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('pbf', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('sys_org_code', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('del_flag', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('avatar_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sys_org_code'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_info_card_id'), 'person_info', ['card_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_info_card_id'), table_name='person_info')
    op.drop_table('person_info')
    op.drop_table('dict_item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_system_log_log_type'), table_name='system_log')
    op.drop_index(op.f('ix_system_log_level'), table_name='system_log')
    op.drop_table('system_log')
    op.drop_index(op.f('ix_robot_code'), table_name='robot')
    op.drop_table('robot')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_dict_type_name'), table_name='dict_type')
    op.drop_index(op.f('ix_dict_type_code'), table_name='dict_type')
    op.drop_table('dict_type')
    # ### end Alembic commands ###
